#!/usr/bin/env bash
# Builds a standalone, unsigned macOS distributable of Roast Telemetry
# -- a real "Roast Telemetry.app" you can zip up and hand to someone
# with no Python/Node installed at all. Must run natively on macOS
# (PyInstaller has no supported cross-compile path).
#
# Prerequisite: scripts/install.sh already run once (sets up .venv with
# every backend + tray dependency). This script only adds pyinstaller on
# top of that and doesn't redo the rest of install.sh's own setup.
#
# Usage:
#   scripts/build-macos.sh            # single-file executable inside the .app (default)
#   scripts/build-macos.sh onedir     # a folder inside the .app instead -- faster
#                                      # startup, no single-exe antivirus-heuristic
#                                      # risk (less of a concern on macOS specifically
#                                      # than Windows, but the same tradeoff exists)
set -euo pipefail
cd "$(dirname "$0")/.."
MODE="${1:-onefile}"
if [[ "$MODE" != "onefile" && "$MODE" != "onedir" ]]; then
  echo "Usage: $0 [onefile|onedir]" >&2
  exit 1
fi

if [[ ! -e .venv/bin/python ]]; then
  echo "No .venv found -- run scripts/install.sh first." >&2
  exit 1
fi

# Optional but recommended: a real .icns instead of PyInstaller's
# generic fallback icon. Only needs doing once -- skipped automatically
# if packaging/icon.icns already exists (e.g. committed after a first
# build, or generated by a previous run of this script).
if [[ ! -e packaging/icon.icns ]]; then
  echo "== Generating packaging/icon.icns from the existing app icons =="
  ICONSET=$(mktemp -d)/icon.iconset
  mkdir -p "$ICONSET"
  # iconutil wants this exact filename set -- doubling the next size up
  # for each @2x slot, standard macOS iconset convention.
  cp frontend/public/icon-16x16.png "$ICONSET/icon_16x16.png"
  cp frontend/public/icon-32x32.png "$ICONSET/icon_16x16@2x.png"
  cp frontend/public/icon-32x32.png "$ICONSET/icon_32x32.png"
  cp frontend/public/icon-64x64.png "$ICONSET/icon_32x32@2x.png"
  cp frontend/public/icon-128x128.png "$ICONSET/icon_128x128.png"
  cp frontend/public/icon-256x256.png "$ICONSET/icon_128x128@2x.png"
  cp frontend/public/icon-256x256.png "$ICONSET/icon_256x256.png"
  cp frontend/public/icon-512x512.png "$ICONSET/icon_256x256@2x.png"
  cp frontend/public/icon-512x512.png "$ICONSET/icon_512x512.png"
  cp frontend/public/icon-1024x1024.png "$ICONSET/icon_512x512@2x.png"
  iconutil -c icns "$ICONSET" -o packaging/icon.icns
  rm -rf "$(dirname "$ICONSET")"
fi

echo "== Building frontend =="
(cd frontend && npm run build)

echo "== Installing pyinstaller + tray dependencies into .venv =="
# The tray deps (pystray/Pillow) are a separate requirements file from
# backend/requirements.txt (see that file's own comment) -- install.sh
# already installs them for the from-source workflow, but re-asserting
# it here too means a build can never silently produce a broken
# "ModuleNotFoundError: No module named 'pystray'" exe just because
# .venv happened to be missing them for some other reason (an older
# install.sh run, a different venv than expected, etc.) -- confirmed
# live on Windows: this exact failure happened before this line existed.
.venv/bin/pip install pyinstaller
.venv/bin/pip install -r scripts/tray_requirements.txt

echo "== Running PyInstaller ($MODE) =="
rm -rf build dist
PACKAGE_MODE="$MODE" .venv/bin/pyinstaller packaging/roast-telemetry.spec --distpath dist --workpath build

echo
echo "Built: dist/Roast Telemetry.app"
echo "Zip that (or use Finder's own Compress) to distribute it."
echo "Unsigned: Gatekeeper will refuse to open it with a plain double-click the first time --"
echo "right-click -> Open -> Open (once) is the standard way past that for an unsigned app,"
echo "not a build error. See packaging/README.md for the full explanation to pass along to whoever you send it to."
